# Generated by Django 4.2.8 on 2025-11-27 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tax_rate",
        ),
    ]
