# Generated by Django 4.2.8 on 2025-11-27 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_order_tax_remove_product_tax_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baladiya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="store_order_email_9efbc4_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="promotion",
        ),
        migrations.RemoveField(
            model_name="order",
            name="promotion_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cash_on_delivery", max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["phone"], name="store_order_phone_2b6c19_idx"),
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.AddIndex(
            model_name="wilaya",
            index=models.Index(fields=["name"], name="store_wilay_name_46fce5_idx"),
        ),
        migrations.AddField(
            model_name="baladiya",
            name="wilaya",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baladiyas",
                to="store.wilaya",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="baladiya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="store.baladiya",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wilaya",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="store.wilaya",
            ),
        ),
        migrations.AddIndex(
            model_name="baladiya",
            index=models.Index(fields=["name"], name="store_balad_name_0abdab_idx"),
        ),
        migrations.AddIndex(
            model_name="baladiya",
            index=models.Index(
                fields=["wilaya"], name="store_balad_wilaya__ed97a1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="baladiya",
            unique_together={("name", "wilaya")},
        ),
    ]
